// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: pb_user.proto

package pb_user

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EnCmdID int32

const (
	EnCmdID_Cmd_NONE    EnCmdID = 0
	EnCmdID_CS_UserInfo EnCmdID = 1
	EnCmdID_SC_UserInfo EnCmdID = 2
)

// Enum value maps for EnCmdID.
var (
	EnCmdID_name = map[int32]string{
		0: "Cmd_NONE",
		1: "CS_UserInfo",
		2: "SC_UserInfo",
	}
	EnCmdID_value = map[string]int32{
		"Cmd_NONE":    0,
		"CS_UserInfo": 1,
		"SC_UserInfo": 2,
	}
)

func (x EnCmdID) Enum() *EnCmdID {
	p := new(EnCmdID)
	*p = x
	return p
}

func (x EnCmdID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnCmdID) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_user_proto_enumTypes[0].Descriptor()
}

func (EnCmdID) Type() protoreflect.EnumType {
	return &file_pb_user_proto_enumTypes[0]
}

func (x EnCmdID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnCmdID.Descriptor instead.
func (EnCmdID) EnumDescriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{0}
}

type EUserRet int32

const (
	EUserRet_Invalid EUserRet = 0
	EUserRet_Success EUserRet = 1
	EUserRet_Failed  EUserRet = 2
)

// Enum value maps for EUserRet.
var (
	EUserRet_name = map[int32]string{
		0: "Invalid",
		1: "Success",
		2: "Failed",
	}
	EUserRet_value = map[string]int32{
		"Invalid": 0,
		"Success": 1,
		"Failed":  2,
	}
)

func (x EUserRet) Enum() *EUserRet {
	p := new(EUserRet)
	*p = x
	return p
}

func (x EUserRet) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EUserRet) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_user_proto_enumTypes[1].Descriptor()
}

func (EUserRet) Type() protoreflect.EnumType {
	return &file_pb_user_proto_enumTypes[1]
}

func (x EUserRet) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EUserRet.Descriptor instead.
func (EUserRet) EnumDescriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{1}
}

type Cmd_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd  EnCmdID `protobuf:"varint,1,opt,name=Cmd,proto3,enum=pb_user.EnCmdID" json:"Cmd,omitempty"`
	Data []byte  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Cmd_Req) Reset() {
	*x = Cmd_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cmd_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cmd_Req) ProtoMessage() {}

func (x *Cmd_Req) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cmd_Req.ProtoReflect.Descriptor instead.
func (*Cmd_Req) Descriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{0}
}

func (x *Cmd_Req) GetCmd() EnCmdID {
	if x != nil {
		return x.Cmd
	}
	return EnCmdID_Cmd_NONE
}

func (x *Cmd_Req) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Cmd_Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret  EUserRet `protobuf:"varint,1,opt,name=Ret,proto3,enum=pb_user.EUserRet" json:"Ret,omitempty"`
	Data []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Cmd_Resp) Reset() {
	*x = Cmd_Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cmd_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cmd_Resp) ProtoMessage() {}

func (x *Cmd_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cmd_Resp.ProtoReflect.Descriptor instead.
func (*Cmd_Resp) Descriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{1}
}

func (x *Cmd_Resp) GetRet() EUserRet {
	if x != nil {
		return x.Ret
	}
	return EUserRet_Invalid
}

func (x *Cmd_Resp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CS_UserInfo_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *CS_UserInfo_Req) Reset() {
	*x = CS_UserInfo_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_UserInfo_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_UserInfo_Req) ProtoMessage() {}

func (x *CS_UserInfo_Req) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_UserInfo_Req.ProtoReflect.Descriptor instead.
func (*CS_UserInfo_Req) Descriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{2}
}

func (x *CS_UserInfo_Req) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SC_UserInfo_Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Score int32  `protobuf:"varint,3,opt,name=Score,proto3" json:"Score,omitempty"`
}

func (x *SC_UserInfo_Resp) Reset() {
	*x = SC_UserInfo_Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_UserInfo_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_UserInfo_Resp) ProtoMessage() {}

func (x *SC_UserInfo_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_UserInfo_Resp.ProtoReflect.Descriptor instead.
func (*SC_UserInfo_Resp) Descriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{3}
}

func (x *SC_UserInfo_Resp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SC_UserInfo_Resp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SC_UserInfo_Resp) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_pb_user_proto protoreflect.FileDescriptor

var file_pb_user_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x62, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x07, 0x43, 0x6d, 0x64, 0x5f,
	0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x03, 0x43, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x10, 0x2e, 0x70, 0x62, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x65, 0x6e, 0x43, 0x6d, 0x64,
	0x49, 0x44, 0x52, 0x03, 0x43, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x08, 0x43,
	0x6d, 0x64, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x45,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x74, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x21, 0x0a, 0x0f, 0x43, 0x53, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x5f,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x10, 0x53, 0x43, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x2a, 0x39, 0x0a, 0x07, 0x65, 0x6e, 0x43, 0x6d, 0x64, 0x49, 0x44, 0x12, 0x0c, 0x0a, 0x08,
	0x43, 0x6d, 0x64, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x53,
	0x5f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x53,
	0x43, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x02, 0x2a, 0x30, 0x0a, 0x08,
	0x45, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x32, 0x38,
	0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x05, 0x44, 0x6f, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x6d, 0x64, 0x5f,
	0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x6d,
	0x64, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_user_proto_rawDescOnce sync.Once
	file_pb_user_proto_rawDescData = file_pb_user_proto_rawDesc
)

func file_pb_user_proto_rawDescGZIP() []byte {
	file_pb_user_proto_rawDescOnce.Do(func() {
		file_pb_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_user_proto_rawDescData)
	})
	return file_pb_user_proto_rawDescData
}

var file_pb_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_user_proto_goTypes = []interface{}{
	(EnCmdID)(0),             // 0: pb_user.enCmdID
	(EUserRet)(0),            // 1: pb_user.EUserRet
	(*Cmd_Req)(nil),          // 2: pb_user.Cmd_Req
	(*Cmd_Resp)(nil),         // 3: pb_user.Cmd_Resp
	(*CS_UserInfo_Req)(nil),  // 4: pb_user.CS_UserInfo_Req
	(*SC_UserInfo_Resp)(nil), // 5: pb_user.SC_UserInfo_Resp
}
var file_pb_user_proto_depIdxs = []int32{
	0, // 0: pb_user.Cmd_Req.Cmd:type_name -> pb_user.enCmdID
	1, // 1: pb_user.Cmd_Resp.Ret:type_name -> pb_user.EUserRet
	2, // 2: pb_user.Server.DoReq:input_type -> pb_user.Cmd_Req
	3, // 3: pb_user.Server.DoReq:output_type -> pb_user.Cmd_Resp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_user_proto_init() }
func file_pb_user_proto_init() {
	if File_pb_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cmd_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cmd_Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_UserInfo_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_UserInfo_Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_user_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_user_proto_goTypes,
		DependencyIndexes: file_pb_user_proto_depIdxs,
		EnumInfos:         file_pb_user_proto_enumTypes,
		MessageInfos:      file_pb_user_proto_msgTypes,
	}.Build()
	File_pb_user_proto = out.File
	file_pb_user_proto_rawDesc = nil
	file_pb_user_proto_goTypes = nil
	file_pb_user_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerClient interface {
	DoReq(ctx context.Context, in *Cmd_Req, opts ...grpc.CallOption) (*Cmd_Resp, error)
}

type serverClient struct {
	cc grpc.ClientConnInterface
}

func NewServerClient(cc grpc.ClientConnInterface) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) DoReq(ctx context.Context, in *Cmd_Req, opts ...grpc.CallOption) (*Cmd_Resp, error) {
	out := new(Cmd_Resp)
	err := c.cc.Invoke(ctx, "/pb_user.Server/DoReq", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
type ServerServer interface {
	DoReq(context.Context, *Cmd_Req) (*Cmd_Resp, error)
}

// UnimplementedServerServer can be embedded to have forward compatible implementations.
type UnimplementedServerServer struct {
}

func (*UnimplementedServerServer) DoReq(context.Context, *Cmd_Req) (*Cmd_Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoReq not implemented")
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_DoReq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cmd_Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).DoReq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_user.Server/DoReq",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).DoReq(ctx, req.(*Cmd_Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb_user.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoReq",
			Handler:    _Server_DoReq_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb_user.proto",
}
